spring.application.name=My_Accountant


# --- JPA Configuration ---
#spring.jpa.hibernate.ddl-auto=update
##use create / create-drop / validate / update
#spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
### --- Database Configuration ---
#spring.datasource.url=jdbc:mysql://localhost:3306/accountant
#spring.datasource.username=root
#spring.datasource.password=nazeer@14
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.hikari.maximum-pool-size=100
#spring.datasource.hikari.minimum-idle=5


### --- JPA Configuration ---
#spring.jpa.hibernate.ddl-auto=update
## use create / create-drop / validate / update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
### --- Database Configuration ---
#spring.datasource.url=jdbc:postgresql://localhost:5432/instamitra
#spring.datasource.username=postgres
#spring.datasource.password=nazeer@14
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.datasource.hikari.maximum-pool-size=100
#spring.datasource.hikari.minimum-idle=5


# application.properties
#spring.redis.host=redis
#spring.redis.port=6379
#spring.redis.timeout=6000
#spring.cache.redis.key-prefix=owner::
#spring.cache.redis.time-to-live = 900s
#spring.cache.redis.use-key-prefix = true
#spring.cache.redis.cache-null-values= false
#spring.cache.type=redis

#jWT-KEY
jwt.secret=6af7!LJv8oN*bYv$Fg7&zj$18@yuS^JP^bTr#wxDqZ#T

spring.boot.admin.client.url=http://localhost:9090
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

logging.pattern.level=%5p [%X{spring.application.name:-},trace=%X{traceId:-},span=%X{spanId:-}]


# Supabase PostgreSQL connection

spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.mwfzwqvzbmoadbmwvxtd
spring.datasource.password=Nazeer@14##


spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

